# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\noumi\Documents\GitHub\tiny-dnn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\noumi\Documents\GitHub\tiny-dnn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	echo >nul && "C:\Program Files\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	echo >nul && "C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install\fast: preinstall\fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	echo >nul && "C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install\fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"cmake\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components\fast: list_install_components

.PHONY : list_install_components\fast

# Special rule for the target install/local
install\local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	echo >nul && "C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install\local

# Special rule for the target install/local
install\local\fast: install\local

.PHONY : install\local\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\noumi\Documents\GitHub\tiny-dnn\CMakeFiles C:\Users\noumi\Documents\GitHub\tiny-dnn\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\noumi\Documents\GitHub\tiny-dnn\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall\fast:
	$(MAKE) -f CMakeFiles\uninstall.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\uninstall.dir\build
.PHONY : uninstall\fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly\fast:
	$(MAKE) -f test\CMakeFiles\Nightly.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\Nightly.dir\build
.PHONY : Nightly\fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental\fast:
	$(MAKE) -f test\CMakeFiles\Experimental.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\Experimental.dir\build
.PHONY : Experimental\fast

#=============================================================================
# Target rules for targets named all_unity

# Build rule for target.
all_unity: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all_unity
.PHONY : all_unity

# fast build rule for target.
all_unity\fast:
	$(MAKE) -f test\CMakeFiles\all_unity.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\all_unity.dir\build
.PHONY : all_unity\fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous\fast:
	$(MAKE) -f test\CMakeFiles\Continuous.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\Continuous.dir\build
.PHONY : Continuous\fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest\fast:
	$(MAKE) -f test\CMakeFiles\NightlyTest.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\NightlyTest.dir\build
.PHONY : NightlyTest\fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck\fast:
	$(MAKE) -f test\CMakeFiles\ContinuousMemCheck.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ContinuousMemCheck.dir\build
.PHONY : ContinuousMemCheck\fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit\fast:
	$(MAKE) -f test\CMakeFiles\NightlySubmit.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\NightlySubmit.dir\build
.PHONY : NightlySubmit\fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck\fast:
	$(MAKE) -f test\CMakeFiles\NightlyMemoryCheck.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\NightlyMemoryCheck.dir\build
.PHONY : NightlyMemoryCheck\fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild\fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalBuild.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ExperimentalBuild.dir\build
.PHONY : ExperimentalBuild\fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart\fast:
	$(MAKE) -f test\CMakeFiles\NightlyStart.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\NightlyStart.dir\build
.PHONY : NightlyStart\fast

#=============================================================================
# Target rules for targets named clean_cotire

# Build rule for target.
clean_cotire: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean_cotire
.PHONY : clean_cotire

# fast build rule for target.
clean_cotire\fast:
	$(MAKE) -f test\CMakeFiles\clean_cotire.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\clean_cotire.dir\build
.PHONY : clean_cotire\fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure\fast:
	$(MAKE) -f test\CMakeFiles\NightlyConfigure.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\NightlyConfigure.dir\build
.PHONY : NightlyConfigure\fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart\fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalStart.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ExperimentalStart.dir\build
.PHONY : ExperimentalStart\fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate\fast:
	$(MAKE) -f test\CMakeFiles\NightlyUpdate.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\NightlyUpdate.dir\build
.PHONY : NightlyUpdate\fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild\fast:
	$(MAKE) -f test\CMakeFiles\NightlyBuild.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\NightlyBuild.dir\build
.PHONY : NightlyBuild\fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage\fast:
	$(MAKE) -f test\CMakeFiles\NightlyCoverage.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\NightlyCoverage.dir\build
.PHONY : NightlyCoverage\fast

#=============================================================================
# Target rules for targets named tiny_dnn_test_unity

# Build rule for target.
tiny_dnn_test_unity: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) tiny_dnn_test_unity
.PHONY : tiny_dnn_test_unity

# fast build rule for target.
tiny_dnn_test_unity\fast:
	$(MAKE) -f test\CMakeFiles\tiny_dnn_test_unity.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\tiny_dnn_test_unity.dir\build
.PHONY : tiny_dnn_test_unity\fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck\fast:
	$(MAKE) -f test\CMakeFiles\NightlyMemCheck.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\NightlyMemCheck.dir\build
.PHONY : NightlyMemCheck\fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate\fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalUpdate.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ExperimentalUpdate.dir\build
.PHONY : ExperimentalUpdate\fast

#=============================================================================
# Target rules for targets named print_device_unity

# Build rule for target.
print_device_unity: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) print_device_unity
.PHONY : print_device_unity

# fast build rule for target.
print_device_unity\fast:
	$(MAKE) -f test\CMakeFiles\print_device_unity.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\print_device_unity.dir\build
.PHONY : print_device_unity\fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild\fast:
	$(MAKE) -f test\CMakeFiles\ContinuousBuild.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ContinuousBuild.dir\build
.PHONY : ContinuousBuild\fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure\fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalConfigure.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ExperimentalConfigure.dir\build
.PHONY : ExperimentalConfigure\fast

#=============================================================================
# Target rules for targets named print_device

# Build rule for target.
print_device: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) print_device
.PHONY : print_device

# fast build rule for target.
print_device\fast:
	$(MAKE) -f test\CMakeFiles\print_device.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\print_device.dir\build
.PHONY : print_device\fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest\fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalTest.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ExperimentalTest.dir\build
.PHONY : ExperimentalTest\fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage\fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalCoverage.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ExperimentalCoverage.dir\build
.PHONY : ExperimentalCoverage\fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck\fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalMemCheck.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ExperimentalMemCheck.dir\build
.PHONY : ExperimentalMemCheck\fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit\fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalSubmit.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ExperimentalSubmit.dir\build
.PHONY : ExperimentalSubmit\fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate\fast:
	$(MAKE) -f test\CMakeFiles\ContinuousUpdate.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ContinuousUpdate.dir\build
.PHONY : ContinuousUpdate\fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart\fast:
	$(MAKE) -f test\CMakeFiles\ContinuousStart.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ContinuousStart.dir\build
.PHONY : ContinuousStart\fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure\fast:
	$(MAKE) -f test\CMakeFiles\ContinuousConfigure.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ContinuousConfigure.dir\build
.PHONY : ContinuousConfigure\fast

#=============================================================================
# Target rules for targets named test_lints

# Build rule for target.
test_lints: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) test_lints
.PHONY : test_lints

# fast build rule for target.
test_lints\fast:
	$(MAKE) -f test\CMakeFiles\test_lints.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\test_lints.dir\build
.PHONY : test_lints\fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest\fast:
	$(MAKE) -f test\CMakeFiles\ContinuousTest.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ContinuousTest.dir\build
.PHONY : ContinuousTest\fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage\fast:
	$(MAKE) -f test\CMakeFiles\ContinuousCoverage.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ContinuousCoverage.dir\build
.PHONY : ContinuousCoverage\fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit\fast:
	$(MAKE) -f test\CMakeFiles\ContinuousSubmit.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\ContinuousSubmit.dir\build
.PHONY : ContinuousSubmit\fast

#=============================================================================
# Target rules for targets named tiny_dnn_test

# Build rule for target.
tiny_dnn_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) tiny_dnn_test
.PHONY : tiny_dnn_test

# fast build rule for target.
tiny_dnn_test\fast:
	$(MAKE) -f test\CMakeFiles\tiny_dnn_test.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\tiny_dnn_test.dir\build
.PHONY : tiny_dnn_test\fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests\fast:
	$(MAKE) -f test\CMakeFiles\run_tests.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\run_tests.dir\build
.PHONY : run_tests\fast

#=============================================================================
# Target rules for targets named clang-tidy

# Build rule for target.
clang-tidy: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clang-tidy
.PHONY : clang-tidy

# fast build rule for target.
clang-tidy\fast:
	$(MAKE) -f test\CMakeFiles\clang-tidy.dir\build.make /nologo -$(MAKEFLAGS) test\CMakeFiles\clang-tidy.dir\build
.PHONY : clang-tidy\fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) gmock
.PHONY : gmock

# fast build rule for target.
gmock\fast:
	$(MAKE) -f googletest-build\googlemock\CMakeFiles\gmock.dir\build.make /nologo -$(MAKEFLAGS) googletest-build\googlemock\CMakeFiles\gmock.dir\build
.PHONY : gmock\fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main\fast:
	$(MAKE) -f googletest-build\googlemock\CMakeFiles\gmock_main.dir\build.make /nologo -$(MAKEFLAGS) googletest-build\googlemock\CMakeFiles\gmock_main.dir\build
.PHONY : gmock_main\fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) gtest
.PHONY : gtest

# fast build rule for target.
gtest\fast:
	$(MAKE) -f googletest-build\googlemock\gtest\CMakeFiles\gtest.dir\build.make /nologo -$(MAKEFLAGS) googletest-build\googlemock\gtest\CMakeFiles\gtest.dir\build
.PHONY : gtest\fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main\fast:
	$(MAKE) -f googletest-build\googlemock\gtest\CMakeFiles\gtest_main.dir\build.make /nologo -$(MAKEFLAGS) googletest-build\googlemock\gtest\CMakeFiles\gtest_main.dir\build
.PHONY : gtest_main\fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... uninstall
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... install
	@echo ... list_install_components
	@echo ... install/local
	@echo ... Nightly
	@echo ... Experimental
	@echo ... all_unity
	@echo ... Continuous
	@echo ... NightlyTest
	@echo ... ContinuousMemCheck
	@echo ... NightlySubmit
	@echo ... NightlyMemoryCheck
	@echo ... ExperimentalBuild
	@echo ... NightlyStart
	@echo ... clean_cotire
	@echo ... NightlyConfigure
	@echo ... ExperimentalStart
	@echo ... NightlyUpdate
	@echo ... NightlyBuild
	@echo ... NightlyCoverage
	@echo ... tiny_dnn_test_unity
	@echo ... NightlyMemCheck
	@echo ... ExperimentalUpdate
	@echo ... print_device_unity
	@echo ... ContinuousBuild
	@echo ... ExperimentalConfigure
	@echo ... print_device
	@echo ... ExperimentalTest
	@echo ... ExperimentalCoverage
	@echo ... ExperimentalMemCheck
	@echo ... ExperimentalSubmit
	@echo ... ContinuousUpdate
	@echo ... ContinuousStart
	@echo ... ContinuousConfigure
	@echo ... test_lints
	@echo ... ContinuousTest
	@echo ... ContinuousCoverage
	@echo ... ContinuousSubmit
	@echo ... tiny_dnn_test
	@echo ... run_tests
	@echo ... clang-tidy
	@echo ... gmock
	@echo ... gmock_main
	@echo ... gtest
	@echo ... gtest_main
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

