FROM tinydnn/tinydnn:dev-ubuntu17.04

MAINTAINER Edgar Riba <edgar.riba@gmail.com>

# Update aptitude with new repo
RUN apt-get update

# Install software
RUN apt-get install -y \
    ocl-icd-opencl-dev \ 
    libviennacl-dev

WORKDIR /opt
RUN git clone https://github.com/naibaf7/libdnn.git && \
    cd libdnn && mkdir build && cd build && \
    cmake .. && make -j2
