g++ -c quantized.cpp -pthread -std=c++11 -D CNN_USE_GEMMLOWP -D CNN_REGISTER_LAYER_DESERIALIZER
g++ quantized.o -o quantized -pthread -std=c++11 -D CNN_USE_GEMMLOWP -D CNN_REGISTER_LAYER_DESERIALIZER

